improve accessibility
FreeTubeApp/FreeTubeApp.io pull request #21
Opened 2022-09-21 03:30 UTC by ChunkyProgrammer

2022-09-21 06:42 UTC, PikachuEXE requested changes
I understand the link text change is to allow better interpretation for link parsers.
But they still should be readable for most people.

2022-09-21 06:42 UTC, PikachuEXE commented on src/privacy.php
> +    <p class="mt-5 sm:ml-16">FreeTube has the option to use Sponsorblock (<a href="https://sponsor.ajay.app/">https://sponsor.ajay.app</a>) within the application. When enabled, FreeTube will make a
You might as well update it as

`Using Sponsorblock within FreeTube subjects you to <a href="https://gist.github.com/ajayyy/aa9f8ded2b573d4f73a3ffa0ef74f796">SponsorBlock privacy policy</a>`

2022-09-21 06:42 UTC, PikachuEXE commented on src/includes/footer.php
> +        <p class="py-2"> The source code for the site can be found here <a href='http://github.com/FreeTubeApp/FreeTubeApp.io' class="text-gray-200">FreeTubeApp.io Source Code</a>.</p>
```suggestion
        <p class="py-2"> The source code for the site can be found on <a href='http://github.com/FreeTubeApp/FreeTubeApp.io' class="text-gray-200">FreeTubeApp.io GitHub Repo</a>.</p>
```

2022-09-22 00:43 UTC, PikachuEXE approved these changes

2022-09-22 07:38 UTC, absidue approved these changes

2022-09-22 08:57 UTC, merged